#TODO: Make implements #from simple_note_taker.src.infra.repo_notes import RepoNotes
from simple_note_taker.src.domain.note import Note

def test_note_should_be_defined_by_a_string():
    assert Note("this is a note").note()=="this is a note"
    
def test_note_should_contain_a_autogenerated_uid():
    id1 = Note("this is another note").id()
    id2 = Note("this is even another note").id()
    assert id1!=id2

